# Bits to Vectors

$$
|b\rangle = 
\begin{bmatrix}
\beta_0 \\
\beta_1
\end{bmatrix}, \quad 
\beta_i \in \{0, 1\}, \quad \text{and} \quad \|b\| = \sqrt{\beta_0^2 + \beta_1^2} = 1
$$

Dot product is used to measure how similar the vectors are to each other.

To get the length of a vector, take the dot product of the vector with itself.

## Bra and Ket
>Ket: 
∣
𝜓
⟩

∣ψ⟩ — column vector, used to describe quantum states

>Bra:
⟨
𝜓
∣

⟨ψ∣ — row vector (complex conjugate transpose of ket), used in inner products

In [4]:
import numpy as np 
import sympy as sp

### SymPy:
>To represent vectors symbolically and turn them into matrix objects.

In [2]:
#ket_0 is a column vector
ket_0 = np.array([[1],[0]])
print(ket_0)

[[1]
 [0]]


In [4]:
sp.Matrix(ket_0)

Matrix([
[1],
[0]])

In [6]:
#ket_1 is a column vector
ket_1 = np.array([[0], [1]])
print(ket_1)

[[0]
 [1]]


In [7]:
sp.Matrix(ket_1)

Matrix([
[0],
[1]])

### Validating a Quantum State Vector

A quantum state vector is valid if its norm squared equals 1:

$$
\|b\|^2 = \beta_0^2 + \beta_1^2 = 1
$$

Validation rule:
- If value = 1 → valid
- Else → invalid


In [12]:
len_ket_0 = np.sqrt(np.sum(ket_0**2))
print(len_ket_0)
#valid vector

1.0


In [13]:
len_ket_1 = np.sqrt(np.sum(ket_1**2))
print(len_ket_1)
#valid vector

1.0


In [19]:
zeros = np.array([[0],[0]])
print(zeros)
sp.Matrix(zeros)

[[0]
 [0]]


Matrix([
[0],
[0]])

In [20]:
len_zeros = np.sqrt(np.sum(zeros**2))
print(len_zeros)
#invalid vector

0.0


In [21]:
ones = np.array([[1], [1]])
print(ones)
sp.Matrix(ones)

[[1]
 [1]]


Matrix([
[1],
[1]])

In [23]:
len_ones = np.sqrt(np.sum(ones**2))
print(len_ones)
#invalid vector

1.4142135623730951


### Length of Vector using Dot Product
> *Row Vector* of first parameter and
> *Column Vector* of second parameter is taken.

In [26]:
dket_0 = np.sqrt(np.vdot(ket_0,ket_0))
print(dket_0)

1.0


In [27]:
dket_1 = np.sqrt(np.vdot(ket_1,ket_1))
print(dket_1)

1.0


In [29]:
dzero = np.sqrt(np.vdot(zeros, zeros))
print(dzero)

0.0


In [30]:
done = np.sqrt(np.vdot(ones, ones))
print(done)

1.4142135623730951


### Orthogonality of Vectors

When two vectors are **orthogonal**, their dot product is zero:

$$
\vec{a} \cdot \vec{b} = 0
$$

This means the vectors are at 90° to each other (i.e., linearly independent in direction).


In [32]:
dket_01 = np.vdot(ket_0,ket_1)
print(dket_01)

0


### Kronecker Product

The Kronecker product is used to perform operations between multi-bit (multi-qubit) vectors or matrices.

It allows us to construct composite systems from smaller ones, such as combining single-qubit states into multi-qubit states.

Example (for vectors):

$$
|a\rangle \otimes |b\rangle = 
\begin{bmatrix} a_0 \\ a_1 \end{bmatrix}
\otimes
\begin{bmatrix} b_0 \\ b_1 \end{bmatrix}
=
\begin{bmatrix}
a_0 b_0 \\
a_0 b_1 \\
a_1 b_0 \\
a_1 b_1
\end{bmatrix}
$$

This is essential in quantum computing for building multi-qubit state vectors and operators.


Let  
$$
b = 10 \quad \text{(decimal: 2)}
$$

We represent the basis state:
$$
|b\rangle = |1\rangle \otimes |0\rangle
$$

In vector notation:
$$
|b\rangle = 
\begin{bmatrix} 0 \\ 1 \end{bmatrix} 
\otimes 
\begin{bmatrix} 1 \\ 0 \end{bmatrix}
= 
\begin{bmatrix} 
0 \cdot \begin{bmatrix} 1 \\ 0 \end{bmatrix} \\
1 \cdot \begin{bmatrix} 1 \\ 0 \end{bmatrix} 
\end{bmatrix}
=
\begin{bmatrix} 
0 \\ 
0 \\
1 \\
0 
\end{bmatrix}
$$


In [36]:
ket_10 = np.kron(ket_1, ket_0)
sp.Matrix(ket_10)

Matrix([
[0],
[0],
[1],
[0]])

# TL;DR:
- **Single Bit**

$$
|b\rangle = 
\begin{bmatrix}
\beta_0 \\
\beta_1
\end{bmatrix},
\quad \beta_i \in \{0,1\},
\quad \sqrt{\beta_0^2 + \beta_1^2} = 1
$$

- **Multi-Bits**

$$
|b\rangle = \bigotimes_{i=1}^{n} |b_{n-i}\rangle 
= |b_{n-1}\rangle \otimes \cdots \otimes |b_i\rangle \otimes \cdots \otimes |b_0\rangle
$$
This forms the tensor product of individual qubit states to build the overall quantum state.
- **General Quantum State over \( N \) Qubits**

$$
|b\rangle =
\begin{bmatrix}
\beta_0 \\
\beta_1 \\
\vdots \\
\beta_{2^N - 1}
\end{bmatrix},
\quad \beta_i \in \mathbb{C},
\quad \sum_{i=0}^{2^N - 1} |\beta_i|^2 = 1
$$




In [40]:
ket_110 = np.kron(np.kron(ket_1, ket_1), ket_0) #for three bit vector
sp.Matrix(ket_110)

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[1],
[0]])