# Introduction To Qubits

In [3]:
import numpy as np
from qiskit.quantum_info import Statevector

In [9]:
ket_0 = Statevector([1,0])
ket_0.draw('latex')

<IPython.core.display.Latex object>

In [7]:
ket_0.probabilities()

array([1., 0.])

In [10]:
ket_p = Statevector([np.sqrt(1/2),np.sqrt(1/2)])
ket_p.draw('latex')

<IPython.core.display.Latex object>

In [11]:
ket_p.probabilities()

array([0.5, 0.5])

In [12]:
ket_p.draw('latex', convention='vector')

<IPython.core.display.Latex object>

In [13]:
ket_m = Statevector.from_label('-')
ket_m.draw('latex')

<IPython.core.display.Latex object>

In [14]:
ket_m.probabilities()

array([0.5, 0.5])

In [19]:
ket_m.sample_counts(50)

{np.str_('0'): np.int64(24), np.str_('1'): np.int64(26)}